spring:
  application:
    name: spring-3-batch

  batch:
    jdbc:
      # add all batch tables
      initialize-schema: always

    job:
      # prevent auto run
      enabled: false
  sql:
    init:
      mode: always

  threads:
    virtual:
      enabled: true